### PR TITLE
Mix Linux and Opengl forks

### PR DESCRIPTION
**Pull request by r-lyeh**
- see https://github.com/erkkah/tigr 
- see https://bitbucket.org/rmitton/tigr/pull-requests/3/enabling-users-to-run-custom-opengl/diff

Adresses #3 
Verified on Windows only.

### CODE REVIEW

**Comment by erkkah** [comment]
Hi @r-lyeh and thanks for the PR!
I'm rather busy with other stuff, but I'll look into it when I get a break.

**Comment by r-lyeh** [comment]
Some Linux reports by @procedural 👍 
```bash
~/Downloads/tigr/examples/demo$ make
g++ demo.cpp ../../tigr.c -s -Os -o demo -I../.. -lGLU -lGL -lX11
../../tigr.c: In function ‘Tigr* tigrWindow(int, int, const char*, int)’:
../../tigr.c:3305:2: error: ‘tigrGAPIResize’ was not declared in this scope
  tigrGAPIResize(bmp, bmp->w, bmp->h);
  ^~~~~~~~~~~~~~
../../tigr.c:3305:2: note: suggested alternative: ‘tigrGAPIBegin’
  tigrGAPIResize(bmp, bmp->w, bmp->h);
  ^~~~~~~~~~~~~~
  tigrGAPIBegin
../../tigr.c: In function ‘void tigrUpdate(Tigr*)’:
../../tigr.c:3446:2: error: ‘tigrGAPIResize’ was not declared in this scope
  tigrGAPIResize(bmp, gwa.width, gwa.height);
  ^~~~~~~~~~~~~~
../../tigr.c:3446:2: note: suggested alternative: ‘tigrGAPIBegin’
  tigrGAPIResize(bmp, gwa.width, gwa.height);
  ^~~~~~~~~~~~~~
  tigrGAPIBegin
Makefile:14: recipe for target 'demo' failed
make: *** [demo] Error 1

~/Downloads/tigr/examples/hello$ make
gcc hello.c ../../tigr.c -s -Os -o hello -I../.. -lGLU -lGL -lX11
../../tigr.c: In function ‘tigrWindow’:
../../tigr.c:3305:2: warning: implicit declaration of function ‘tigrGAPIResize’; did you mean ‘tigrGAPIBegin’? [-Wimplicit-function-declaration]
  tigrGAPIResize(bmp, bmp->w, bmp->h);
  ^~~~~~~~~~~~~~
  tigrGAPIBegin
/tmp/cch9DnqE.o: In function `tigrWindow':
tigr.c:(.text+0x30ce): undefined reference to `tigrGAPIBegin'
tigr.c:(.text+0x30de): undefined reference to `tigrGAPIResize'
/tmp/cch9DnqE.o: In function `tigrGAPIDestroy':
tigr.c:(.text+0x3124): undefined reference to `tigrGAPIBegin'
tigr.c:(.text+0x315f): undefined reference to `tigrGAPIEnd'
/tmp/cch9DnqE.o: In function `tigrUpdate':
tigr.c:(.text+0x3690): undefined reference to `tigrGAPIResize'
/tmp/cch9DnqE.o: In function `tigrBeginOpenGL':
tigr.c:(.text+0x1a55): undefined reference to `tigrGAPIBegin'
collect2: error: ld returned 1 exit status
Makefile:14: recipe for target 'hello' failed
make: *** [hello] Error 1
~/Downloads/tigr/examples/opengl$ make
gcc opengl.c ../../tigr.c -s -Os -o opengl -I../.. 
opengl.c:7:10: fatal error: OpenGL/gl3.h: No such file or directory
 #include <OpenGL/gl3.h>
          ^~~~~~~~~~~~~~
compilation terminated.
../../tigr.c: In function ‘tigrWindow’:
../../tigr.c:3305:2: warning: implicit declaration of function ‘tigrGAPIResize’; did you mean ‘tigrGAPIBegin’? [-Wimplicit-function-declaration]
  tigrGAPIResize(bmp, bmp->w, bmp->h);
  ^~~~~~~~~~~~~~
  tigrGAPIBegin
Makefile:12: recipe for target 'opengl' failed
make: *** [opengl] Error 1
```

**Comment by r-lyeh** [comment]
I managed to compile now on a virtual xubuntu distro. However, I cannot display demos properly. Errors happen as well if working with master branch, so I guess there is something wrong with my virtualized OS distro definitely (Virtualbox+xubuntu).

**Comment by r-lyeh** [comment]
@procedural tested Linux with latest commit (seems to work imo).
Anyone testing OSX plz? :D

https://cdn.discordapp.com/attachments/460320687496888321/672120951621681163/1.png
https://cdn.discordapp.com/attachments/460320687496888321/672120956134883338/2.png
https://cdn.discordapp.com/attachments/460320687496888321/672120958735089673/3.png

**Comment by erkkah** [comment]
@r-lyeh, I've had a first look at the code and did a test run on Windows (will check on Mac later).
I noticed that the opengl version really loads both cpu and gpu compared to the dx version.
Is this something you have noticed? The difference is quite dramatic.

**Comment by r-lyeh** [comment]
I think opengl is not using any 60fps lock, as opposed to dx. So you may be running a 800 fps build :)

**Comment by erkkah** [comment]
@r-lyeh, I have tested on Linux an Mac now, it seems to work fine. Your opengl example was great, since it uncovered an existing bug in the Mac implementation that I will look into.

I think we need to look into fps locking so we can try get the same behavior regardless of platform and driver defaults.

Since I want to pull more things in and test together, can you re-submit the PR to the "develop" branch I just created?

**Comment by r-lyeh** [comment]
updated PR in develop branch.
also, regarding FPS, I've commited some swap/vsync code in my fork. can you test that plz?

**Comment by r-lyeh** [comment]
ps: forgot to say that we should test my fps-vsync fix in all major gpu cards (nvidia,amd,intel), since solution depends on vendor drivers. for now, tested on intel gpu card.

**Pull request closed without merging**
