### PR TITLE
Various fixes

### LINKED ISSUE #44: fullscreen not working in X11
pressing F in examples/flags does nothing

### LINKED ISSUE #45: headless mode not working on Linux
examples/headless can't compile

```
gcc headless.c ../../tigr.c -Os -o headless -fsanitize=undefined -I../.. -Wall -DTIGR_HEADLESS -s -lGLU -lGL -lX11
../../tigr.c:114:5: error: unknown type name ‘GLXContext’
  114 |     GLXContext glc;
      |     ^~~~~~~~~~
make: *** [Makefile:14: headless] Error 1
```

### PR DESCRIPTION
**Pull request by iacore**
Closes #44 
Closes #45

### CODE REVIEW

**Comment by iacore** [comment]
I'm worried about too many conversions between signed and unsigned throughout the source code.

**Comment by erkkah** [comment]
Hi there.
Thanks for the fixes. I wasn't quite done with headless, so thanks for the X11 - fix.

Re signed/unsigned - there is a lot that could be cleaned up with higher warning levels and what not. I have done local incremental fixes to the codebase since I took over the project. I'm sure there is more to worry about :)

Thanks again for the PR, I'll take a look.

**Comment by erkkah** [comment]
Checked on my end, both fullscreen variants work here. Just out of curiosity, what is the setup where the old implementation does not work?

**Comment by iacore** [comment]
tiling window manager.
X11 has min/max width/height window hints. The window manager may not respect one-time setting of window size.

The original code set the window size once, but that's fake fullscreen. The window type is still _NET_WM_NORMAL, so my tiling window manager doesn't respect it.

**Pull request merged**
